### PR TITLE
added score and powerups

### PR DESCRIPTION
**Pull request by Jake0Tron**
added score and some basic powerups. cleaned up some code in helper funcs for readability

### CODE REVIEW

**Comment by VRamazing** [comment]
I can't see pipes being generated and Could you please reduce the probability of generation of powerups.
I think a powerup to slow speed would be good and would be pretty easy to create.Let's focus on just one powerup.Reducing the ball size is also good.Just make it temporary.I like the colour you have chosen.

**Comment by Jake0Tron** [comment]
I'll make some adjustments tonight, seems that the prev. merges made some things change..

**Comment by VRamazing** [comment]
Thanks @Jake0Tron that would be great.

**Review by VRamazing — CHANGES_REQUESTED** [review]
Great Code.There is some issue with powerup collision.When the ball overlaps it doesn't seem to pick it up and when i just go around it.It picks it.And I don't think there is a need to display the speed and width.Just lives would be sufficient.

**Comment by VRamazing** [comment]
@Jake0Tron Are you still interested taking up this issue?

**Comment by Jake0Tron** [comment]
Work has picked up so I don't have much time to get back into it. Feel free
to pick up or hand off

**Pull request closed without merging**
