### PR TITLE
Add lives to the ball #2

### PR DESCRIPTION
**Pull request by Charlie43**
Added basic lives support.
Game resets on failure, and only ends once the player is out of lives.

### CODE REVIEW

**Comment by VRamazing** [comment]
There is some issue with the code isGameOver function. I am able to die 4 times.And make sure either change gameOver boolean var to some different name as it leads to confusion with isGameOver function.You can rename it to something like crosses boundary or reuse isOutsideBoundary function

**Review by VRamazing — CHANGES_REQUESTED** [review]
There is some issue with the code isGameOver function. I am able to die 4 times.And make sure either change gameOver boolean var to some different name as it leads to confusion with isGameOver function.You can rename it to something like crosses boundary or reuse isOutsideBoundary function

**Comment by Charlie43** [comment]
Renamed the isGameOver function to checkLives, and fixed the lives issue; let me know if that's okay :)

**Comment by VRamazing** [comment]
Great work @Charlie43 .Merging right now.

**Pull request merged**
