### PR TITLE
Added fullscreen, animation for death, and difficulty.

### PR DESCRIPTION
**Pull request by cedric-h**
Hope this helps! :D

### CODE REVIEW

**Review by VRamazing — CHANGES_REQUESTED** [review]
I love the death animation.In case of difficulty, I think the gap between pipes suddenly becomes impossible to cross.Its like an avalanche.A better approach would be to complement the decrease in distance between pipe.Increase the speed of lift and drop of ball.Or you can keep distance between pipes same and increase the speed with they progress towards ball.

**Comment by cedric-h** [comment]
I'll get this done ASAP.

**Comment by cedric-h** [comment]
Sorry, ASAP kept getting pushed farther and farther back.

**Comment by cedric-h** [comment]
Alright, take a peek at what I have so far. I've made the velocity of our orb change gradually, and I've also made the rate at which the velocity changes change gradually, to the effect that at the beginning of the game, the player is slow, and they glide about gradually, but then over time they gain more and more agility and are soon flying past obstacles with astonishing speed. I've gotten as high as 204, whereas I could seldom pass 50 in the old version.

**Review by VRamazing — APPROVED** [review]
Awesome work

**Pull request merged**
